
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For local SQLite:
    url: env("DATABASE_URL") || "file:./dev.db", 
    
    // OR if you are using Turso:
    // url: env("DATABASE_URL"), // e.g. libsql://your-db.turso.io
  },
});
